-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 15:20:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  `email` VARCHAR(80) NULL,
  `contrasena` VARCHAR(80) NULL,
  `perfil` VARCHAR(80) NULL,
  `firma` VARCHAR(80) NULL,
  `telefono` VARCHAR(12) NULL,
  `prefijotelefono` VARCHAR(4) NULL,
  `prefijonombre` VARCHAR(5) NULL,
  `registromedico` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especializacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especializacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auxiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auxiliar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Institucion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(80) NULL,
  `logo` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Especializacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Especializacion` (
  `Usuario_id` INT NULL,
  `Especializacion_id` INT NULL,
  INDEX `UE_U_idx` (`Usuario_id` ASC) VISIBLE,
  INDEX `UE_E_idx` (`Especializacion_id` ASC) VISIBLE,
  CONSTRAINT `UE_U`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UE_E`
    FOREIGN KEY (`Especializacion_id`)
    REFERENCES `mydb`.`Especializacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Auxiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Auxiliar` (
  `Usuario_id` INT NULL,
  `Auxiliar_id` INT NULL,
  INDEX `UA_U_idx` (`Usuario_id` ASC) VISIBLE,
  INDEX `UA_A_idx` (`Auxiliar_id` ASC) VISIBLE,
  CONSTRAINT `UA_U`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UA_A`
    FOREIGN KEY (`Auxiliar_id`)
    REFERENCES `mydb`.`Auxiliar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Institucion` (
  `Usuario_id` INT NULL,
  `Institucion_id` INT NULL,
  INDEX `UI_U_idx` (`Usuario_id` ASC) VISIBLE,
  INDEX `UI_I_idx` (`Institucion_id` ASC) VISIBLE,
  CONSTRAINT `UI_U`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UI_I`
    FOREIGN KEY (`Institucion_id`)
    REFERENCES `mydb`.`Institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
